### ISSUE TITLE
“models/: Contains the neural networks used. Also contains the trained models for each task.”

### ISSUE THREAD

**Issue by Capri2014** [AdaCompNUS/magic#2]
I did not see the trained model in this folder, could you elaborate more on how to play with different examples shown in paper?

**Comment by LeeYiyuan** [comment]
Hi @Capri2014, so sorry about that! We had `.gitignore`'ed the trained models by accident. It has now been added to the `models/folder`. The instructions have also been updated with examples on how to run the scripts.
