### ISSUE TITLE
Opencv does not work in evaluate.py script

### ISSUE THREAD

**Issue by YC-Liang** [AdaCompNUS/magic#3]
Dear Author,

I am playing with the code from the master branch however I encounter issues when running the evaluate.py script. The direct error message says,

best_value = float(self.process.stdout.readline().decode('utf8').strip())
ValueError: could not convert string to float: ''

So I tried to turn visualisation option to false and the evaluate script works without displaying the environment per step.
Then I try to see whether the TastTest c++ file can render the environment without Python calling it, and indeed the script works and I can get environment displayed with random actions. 

Based on above, I guess the issue is caused by Python calling the c++ files and somehow OpenCV in this case stopped working. But I haven't found a direct solution yet, any suggestions would be much appreciated.

Thanks,
James

**Comment by LeeYiyuan** [comment]
Hi James,

Thanks for bringing this up!

Could you provide more details on which `evaluate.py` script are you using, as well as the (full list of) arguments used?

**Comment by YC-Liang** [comment]
I used the `evaluted.py` file from mdespot_magic folder and ran the command from the ReadMe file,
`python3 evaluate.py --task=LightDark --macro-length=8 --model-path=../models/learned_LightDark_8 --model-index=500000`

**Comment by LeeYiyuan** [comment]
It seems like I have made a typo in the readme. Could you try the following?

```python3 evaluate.py --task=LightDark --macro-length=8 --model-path=../models/learned_LightDark_8/gen_model.pt.00500000```

**Comment by LeeYiyuan** [comment]
Additionally, it is possible that some conda/pip opencv packages are conflicting with the opencv version that the cpp codes are compiled with. You can check which version of opencv is being used by running `ldd TaskTestLightDark  | grep cv`.

You could try to remove everything in `conda list | grep cv` and `pip list | grep cv`, and then recompile the cpp codes again.

**Comment by YC-Liang** [comment]
`python3 evaluate.py --task=LightDark --macro-length=8 --model-path=../models/learned_LightDark_8/gen_model.pt.00500000` didn't work with the error

model_path = model_path.format(args.model_index)
TypeError: unsupported format string passed to NoneType.__format__

I did install opencv python and opencv c++ source code, potentially they do conflict each other. I will mess around to see what happens. Thanks.

**Comment by YC-Liang** [comment]
Just an update, I have fixed the issue. There is no need to modify the OpenCV c++ source, all I did is to remove Opencv-python from pip and install it again using conda, and everything worked. Thanks very much for your advices!

PS: I think the original command in the ReadMe file is correct `python3 evaluate.py --task=LightDark --macro-length=8 --model-path=../models/learned_LightDark_8 --model-index=500000`

**Comment by LeeYiyuan** [comment]
That's great news! I'm glad it worked :)

> PS: I think the original command in the ReadMe file is correct python3 evaluate.py --task=LightDark --macro-length=8 --model-path=../models/learned_LightDark_8 --model-index=500000

The `--model-index` parameter is only supported by `benchmark.py` but not `evaluate.py`. It was used in `evaluate.py` in a very early version but should not have been pushed here; but I'll give it a look again!
